title: Yard Bird Observer
description: >- # this means to ignore newlines until "baseurl:"
  All the birds spotted in a single quarter acre suburban yard in Thornton, Colorado USA.
baseurl: "/" 
css-dir: "assets/css/"
linkedin: "https://www.linkedin.com/in/christanfergus/"
url: "https://yardbird.observer" 
personal-site: "https://christanfergus.com"
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
markdown: kramdown
future: true
sass:
  sass_dir: assets/stylesheets
  style: compressed
  sourcemap: always 
assets:
  source_maps: true
  sources:
  - assets/stylesheets